name: build deploy hugo

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.65.2"

      - name: Build Static Site
        run: hugo --minify

      - name: Deploy to S3
        run: |
          ls -R
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends s3cmd
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get clean -y
          echo "${{ secrets.S3CMD_CONFIG }}" > /home/runner/.s3cfg
          s3cmd sync --delete-removed --no-mime-magic --guess-mime-type --add-header="Cache-Control:max-age=3600" -P -r public/* s3://${{ secrets.AWS_S3_BUCKET }}/
