name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # v2 does not have submodules option now

      # with:
      #   submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.65.2"
          # extended: true

      - name: Build
        run: hugo --minify

      - uses: chrislennon/action-aws-cli@v1.1
      # All commands after this point have access to the AWS CLI
      - name: Deploy
        run: aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }}/ --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
